In [ ]:
18/06/2026

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv('student.csv')
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [4]:
df.shape

(10, 5)

In [5]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [8]:
df.dtypes

roll       int64
name      object
class     object
marks    float64
age        int64
dtype: object

In [13]:
#this returns the values from the 1st index in a tabel
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [14]:
df.head(7)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19

In [11]:
#this returns the values from the last index in a tabel
    df.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [15]:

df.tail(3)

   roll   name class  marks  age
7     8  amita    BE  68.33   23
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

In [16]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [19]:
df.T

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [20]:
#slicing

In [21]:
# two options
# 1 --> index based --iloc
#2 --->coloumn based --

In [22]:
df.iloc[1:4,1:4]

      name class  marks
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66

In [23]:
df.iloc[2:5,2:6]

  class  marks  age
2    BE  76.88   19
3    TE  69.66   20
4    TE  63.28   20

In [26]:
df.iloc[1:5,[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28

In [33]:
df.iloc[[1,2,3,4,6],[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28
6     7     amar  65.34

In [35]:
df.iloc[5,1]='geet'
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [36]:
df.iloc[9:10,4:9]

   age
9   21

In [39]:
df.iloc[8:9,3:8]

   marks  age
8  56.75   20

In [40]:
# loc

In [41]:
df.loc[2:5,'name']

2     aniket
3    ajinkya
4       asha
5       geet
Name: name, dtype: object

In [42]:
df.loc[2:5,['name','class']]

      name class
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE

In [45]:
df.loc[:,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [46]:
df.loc[0:9,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [47]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [48]:
df[['name','class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE
6     amar    BE
7    amita    BE
8     amol    TE
9    anmol    BE

In [52]:
#methods on columns/series

In [53]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [54]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5       GEET
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [55]:
df['class'].str.lower()

0    te
1    te
2    be
3    te
4    te
5    be
6    be
7    be
8    te
9    be
Name: class, dtype: object

In [59]:
gender =['m','m','m','m','f','f','m','m','m','m']

In [60]:
df['gender']=gender

In [61]:
df

   roll     name class  marks  age gender
0     1     anil    TE  56.77   22      m
1     2     amit    TE  59.77   21      m
2     3   aniket    BE  76.88   19      m
3     4  ajinkya    TE  69.66   20      m
4     5     asha    TE  63.28   20      f
5     6     geet    BE  49.55   20      f
6     7     amar    BE  65.34   19      m
7     8    amita    BE  68.33   23      m
8     9     amol    TE  56.75   20      m
9    10    anmol    BE  78.66   21      m

In [62]:
df['roll']=df['roll']+100

In [63]:
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106     geet    BE  49.55   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      m
8   109     amol    TE  56.75   20      m
9   110    anmol    BE  78.66   21      m

In [64]:
#add a new column cgp
#values sholud = marks/10+1.5

In [67]:
df['cgp']=df['marks']/10+1.5

In [68]:
df

   roll     name class  marks  age gender   cgpc    cgp
0   101     anil    TE  56.77   22      m  7.177  7.177
1   102     amit    TE  59.77   21      m  7.477  7.477
2   103   aniket    BE  76.88   19      m  9.188  9.188
3   104  ajinkya    TE  69.66   20      m  8.466  8.466
4   105     asha    TE  63.28   20      f  7.828  7.828
5   106     geet    BE  49.55   20      f  6.455  6.455
6   107     amar    BE  65.34   19      m  8.034  8.034
7   108    amita    BE  68.33   23      m  8.333  8.333
8   109     amol    TE  56.75   20      m  7.175  7.175
9   110    anmol    BE  78.66   21      m  9.366  9.366

In [69]:
df.sort_values(by='name')

   roll     name class  marks  age gender   cgpc    cgp
3   104  ajinkya    TE  69.66   20      m  8.466  8.466
6   107     amar    BE  65.34   19      m  8.034  8.034
1   102     amit    TE  59.77   21      m  7.477  7.477
7   108    amita    BE  68.33   23      m  8.333  8.333
8   109     amol    TE  56.75   20      m  7.175  7.175
2   103   aniket    BE  76.88   19      m  9.188  9.188
0   101     anil    TE  56.77   22      m  7.177  7.177
9   110    anmol    BE  78.66   21      m  9.366  9.366
4   105     asha    TE  63.28   20      f  7.828  7.828
5   106     geet    BE  49.55   20      f  6.455  6.455

In [70]:
df

   roll     name class  marks  age gender   cgpc    cgp
0   101     anil    TE  56.77   22      m  7.177  7.177
1   102     amit    TE  59.77   21      m  7.477  7.477
2   103   aniket    BE  76.88   19      m  9.188  9.188
3   104  ajinkya    TE  69.66   20      m  8.466  8.466
4   105     asha    TE  63.28   20      f  7.828  7.828
5   106     geet    BE  49.55   20      f  6.455  6.455
6   107     amar    BE  65.34   19      m  8.034  8.034
7   108    amita    BE  68.33   23      m  8.333  8.333
8   109     amol    TE  56.75   20      m  7.175  7.175
9   110    anmol    BE  78.66   21      m  9.366  9.366

In [71]:
df.sort_values(by='marks')

   roll     name class  marks  age gender   cgpc    cgp
5   106     geet    BE  49.55   20      f  6.455  6.455
8   109     amol    TE  56.75   20      m  7.175  7.175
0   101     anil    TE  56.77   22      m  7.177  7.177
1   102     amit    TE  59.77   21      m  7.477  7.477
4   105     asha    TE  63.28   20      f  7.828  7.828
6   107     amar    BE  65.34   19      m  8.034  8.034
7   108    amita    BE  68.33   23      m  8.333  8.333
3   104  ajinkya    TE  69.66   20      m  8.466  8.466
2   103   aniket    BE  76.88   19      m  9.188  9.188
9   110    anmol    BE  78.66   21      m  9.366  9.366

In [72]:
#sort by class and then marks simultaneously and check the result

In [74]:
df.sort_values(by=['class','marks'])

   roll     name class  marks  age gender   cgpc    cgp
5   106     geet    BE  49.55   20      f  6.455  6.455
6   107     amar    BE  65.34   19      m  8.034  8.034
7   108    amita    BE  68.33   23      m  8.333  8.333
2   103   aniket    BE  76.88   19      m  9.188  9.188
9   110    anmol    BE  78.66   21      m  9.366  9.366
8   109     amol    TE  56.75   20      m  7.175  7.175
0   101     anil    TE  56.77   22      m  7.177  7.177
1   102     amit    TE  59.77   21      m  7.477  7.477
4   105     asha    TE  63.28   20      f  7.828  7.828
3   104  ajinkya    TE  69.66   20      m  8.466  8.466

In [77]:
df['marks'].mean()

np.float64(64.499)

In [78]:
df['marks'].max()

78.66

In [79]:
df.describe()

            roll      marks        age       cgpc        cgp
count   10.00000  10.000000  10.000000  10.000000  10.000000
mean   105.50000  64.499000  20.500000   7.949900   7.949900
std      3.02765   9.207179   1.269296   0.920718   0.920718
min    101.00000  49.550000  19.000000   6.455000   6.455000
25%    103.25000  57.520000  20.000000   7.252000   7.252000
50%    105.50000  64.310000  20.000000   7.931000   7.931000
75%    107.75000  69.327500  21.000000   8.432750   8.432750
max    110.00000  78.660000  23.000000   9.366000   9.366000

In [80]:
#groupby

In [81]:
gr=df.groupby('class')

In [82]:
gr.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [84]:
gr.get_group('BE')

   roll    name class  marks  age gender   cgpc    cgp
2   103  aniket    BE  76.88   19      m  9.188  9.188
5   106    geet    BE  49.55   20      f  6.455  6.455
6   107    amar    BE  65.34   19      m  8.034  8.034
7   108   amita    BE  68.33   23      m  8.333  8.333
9   110   anmol    BE  78.66   21      m  9.366  9.366

In [85]:
gr.min()

       roll     name  marks  age gender   cgpc    cgp
class
BE      103     amar  49.55   19      f  6.455  6.455
TE      101  ajinkya  56.75   20      f  7.175  7.175

In [86]:
gr['marks'].mean()

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

In [87]:
df['marks']>60

0    False
1    False
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: marks, dtype: bool

In [88]:
df[df['marks']>60]

   roll     name class  marks  age gender   cgpc    cgp
2   103   aniket    BE  76.88   19      m  9.188  9.188
3   104  ajinkya    TE  69.66   20      m  8.466  8.466
4   105     asha    TE  63.28   20      f  7.828  7.828
6   107     amar    BE  65.34   19      m  8.034  8.034
7   108    amita    BE  68.33   23      m  8.333  8.333
9   110    anmol    BE  78.66   21      m  9.366  9.366

In [89]:
#filter the data of those student --> marks>60 and belongs to BC class

In [90]:
filtered_df = df[(df["marks"] > 60) & (df["class"] == "BE")]
filtered_df

   roll    name class  marks  age gender   cgpc    cgp
2   103  aniket    BE  76.88   19      m  9.188  9.188
6   107    amar    BE  65.34   19      m  8.034  8.034
7   108   amita    BE  68.33   23      m  8.333  8.333
9   110   anmol    BE  78.66   21      m  9.366  9.366

In [91]:
#drop--> drop column and rows

In [92]:
df.drop(4)

   roll     name class  marks  age gender   cgpc    cgp
0   101     anil    TE  56.77   22      m  7.177  7.177
1   102     amit    TE  59.77   21      m  7.477  7.477
2   103   aniket    BE  76.88   19      m  9.188  9.188
3   104  ajinkya    TE  69.66   20      m  8.466  8.466
5   106     geet    BE  49.55   20      f  6.455  6.455
6   107     amar    BE  65.34   19      m  8.034  8.034
7   108    amita    BE  68.33   23      m  8.333  8.333
8   109     amol    TE  56.75   20      m  7.175  7.175
9   110    anmol    BE  78.66   21      m  9.366  9.366

In [94]:
df.drop([6,8])

   roll     name class  marks  age gender   cgpc    cgp
0   101     anil    TE  56.77   22      m  7.177  7.177
1   102     amit    TE  59.77   21      m  7.477  7.477
2   103   aniket    BE  76.88   19      m  9.188  9.188
3   104  ajinkya    TE  69.66   20      m  8.466  8.466
4   105     asha    TE  63.28   20      f  7.828  7.828
5   106     geet    BE  49.55   20      f  6.455  6.455
7   108    amita    BE  68.33   23      m  8.333  8.333
9   110    anmol    BE  78.66   21      m  9.366  9.366

In [95]:
#drop name column

In [97]:
df.drop('name',axis=1)

   roll class  marks  age gender   cgpc    cgp
0   101    TE  56.77   22      m  7.177  7.177
1   102    TE  59.77   21      m  7.477  7.477
2   103    BE  76.88   19      m  9.188  9.188
3   104    TE  69.66   20      m  8.466  8.466
4   105    TE  63.28   20      f  7.828  7.828
5   106    BE  49.55   20      f  6.455  6.455
6   107    BE  65.34   19      m  8.034  8.034
7   108    BE  68.33   23      m  8.333  8.333
8   109    TE  56.75   20      m  7.175  7.175
9   110    BE  78.66   21      m  9.366  9.366

In [98]:
df.drop('age',axis=1)

   roll     name class  marks gender   cgpc    cgp
0   101     anil    TE  56.77      m  7.177  7.177
1   102     amit    TE  59.77      m  7.477  7.477
2   103   aniket    BE  76.88      m  9.188  9.188
3   104  ajinkya    TE  69.66      m  8.466  8.466
4   105     asha    TE  63.28      f  7.828  7.828
5   106     geet    BE  49.55      f  6.455  6.455
6   107     amar    BE  65.34      m  8.034  8.034
7   108    amita    BE  68.33      m  8.333  8.333
8   109     amol    TE  56.75      m  7.175  7.175
9   110    anmol    BE  78.66      m  9.366  9.366

In [99]:
df.drop(3)

   roll    name class  marks  age gender   cgpc    cgp
0   101    anil    TE  56.77   22      m  7.177  7.177
1   102    amit    TE  59.77   21      m  7.477  7.477
2   103  aniket    BE  76.88   19      m  9.188  9.188
4   105    asha    TE  63.28   20      f  7.828  7.828
5   106    geet    BE  49.55   20      f  6.455  6.455
6   107    amar    BE  65.34   19      m  8.034  8.034
7   108   amita    BE  68.33   23      m  8.333  8.333
8   109    amol    TE  56.75   20      m  7.175  7.175
9   110   anmol    BE  78.66   21      m  9.366  9.366

In [100]:
#drop name and class

In [102]:
df.drop(['name','class'],axis=1)

   roll  marks  age gender   cgpc    cgp
0   101  56.77   22      m  7.177  7.177
1   102  59.77   21      m  7.477  7.477
2   103  76.88   19      m  9.188  9.188
3   104  69.66   20      m  8.466  8.466
4   105  63.28   20      f  7.828  7.828
5   106  49.55   20      f  6.455  6.455
6   107  65.34   19      m  8.034  8.034
7   108  68.33   23      m  8.333  8.333
8   109  56.75   20      m  7.175  7.175
9   110  78.66   21      m  9.366  9.366

In [108]:
df.drop(['gender','cgp'],axis=1,inplace=True)

In [109]:
df

   roll     name class  marks  age   cgpc
0   101     anil    TE  56.77   22  7.177
1   102     amit    TE  59.77   21  7.477
2   103   aniket    BE  76.88   19  9.188
3   104  ajinkya    TE  69.66   20  8.466
4   105     asha    TE  63.28   20  7.828
5   106     geet    BE  49.55   20  6.455
6   107     amar    BE  65.34   19  8.034
7   108    amita    BE  68.33   23  8.333
8   109     amol    TE  56.75   20  7.175
9   110    anmol    BE  78.66   21  9.366

In [110]:
#create a dataframe newdf
#columns-->roll,gender,cgp
#roll column will hav the same values as that of in the df dataframe

In [111]:
newdf=pd.DataFrame({
    'roll':df['roll'],
    'gender':gender,
    'cgp':df['marks']/10+1.5
})

In [112]:
newdf

   roll gender    cgp
0   101      m  7.177
1   102      m  7.477
2   103      m  9.188
3   104      m  8.466
4   105      f  7.828
5   106      f  6.455
6   107      m  8.034
7   108      m  8.333
8   109      m  7.175
9   110      m  9.366

In [113]:
pd.merge(df,newdf)

   roll     name class  marks  age   cgpc gender    cgp
0   101     anil    TE  56.77   22  7.177      m  7.177
1   102     amit    TE  59.77   21  7.477      m  7.477
2   103   aniket    BE  76.88   19  9.188      m  9.188
3   104  ajinkya    TE  69.66   20  8.466      m  8.466
4   105     asha    TE  63.28   20  7.828      f  7.828
5   106     geet    BE  49.55   20  6.455      f  6.455
6   107     amar    BE  65.34   19  8.034      m  8.034
7   108    amita    BE  68.33   23  8.333      m  8.333
8   109     amol    TE  56.75   20  7.175      m  7.175
9   110    anmol    BE  78.66   21  9.366      m  9.366

In [114]:
#concat

In [123]:
#lod student5.csv

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [125]:
newdf=pd.read_csv('student5.csv')

In [126]:
newdf

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [122]:
pd.concat([df,newdf],ignore_index=True)

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20
5     1   surbhi    TE  67.44   23
6     2    sujay    TE  74.12   22
7     3  subhash    BE  82.44   21
8     4   sachin    TE  59.33   21
9     5  shalini    TE  63.45   20

In [127]:
f=df[(df['marks']>60)&(df['class']=='BE')]

In [128]:
f.to_csv('op.csv',index=False)

In [129]:
f

   roll     name class  marks  age
2     3  subhash    BE  82.44   21