In [2]:
import pandas as pd

In [3]:
roll=pd.Series([1,2,3,4,5])
name=pd.Series(['Apurva','Su','minu','ayu','shraddha'])
marks=pd.Series([89,79,80,90,67])

In [4]:
pd.DataFrame({
    'id':roll,
    'name':name,
    'mark':marks
})

   id      name  mark
0   1    Apurva    89
1   2        Su    79
2   3      minu    80
3   4       ayu    90
4   5  shraddha    67

In [4]:
df

   id      name  mark
0   1    Apurva    89
1   2        Su    79
2   3      minu    80
3   4       ayu    90
4   5  shraddha    67

In [5]:
df.ndim

2

In [6]:
df.shape

(5, 3)

In [7]:
df.size

15

In [9]:
df.columns

Index(['id', 'name', 'mark'], dtype='object')

In [10]:
pwd

'C:\\Users\\Hp'

In [11]:
df=pd.read_csv("student.csv")

In [12]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [13]:
col=['roll','name','class','marks','age']

In [14]:
df=pd.read_csv('student1.csv',names=col)
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [16]:
df=pd.read_csv('student3.tsv')
df

  roll\tname\tclass\tmarks\tage
0        1\tanil\tTE\t56.77\t22
1        2\tamit\tTE\t59.77\t21
2      3\taniket\tBE\t76.88\t19
3     4\tajinkya\tTE\t69.66\t20
4        5\tasha\tTE\t63.28\t20
5      6\tayesha\tBE\t49.55\t20
6        7\tamar\tBE\t65.34\t19
7       8\tamita\tBE\t68.33\t23
8        9\tamol\tTE\t56.75\t20
9      10\tanmol\tBE\t78.66\t21

In [17]:
df=pd.read_csv('student3.csv')
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [5]:
import pandas as pd

In [6]:
df=pd.read_csv('Student3.tsv', sep = '\t')